In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('Day8_Ecommerce_Sales_Dataset.csv')
df.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [3]:

df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    datetime64[ns]
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(4), object(6)
memory usage: 10.3+ KB

In [4]:
print("Shape (rows, columns):", df.shape)
print("\nColumns:", list(df.columns))
print("\nMissing values per column:\n", df.isnull().sum())
df.select_dtypes(include='number').describe()

Shape (rows, columns): (100, 13)

Columns: ['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']

Missing values per column:
 Order_ID            0
Order_Date          0
Customer            0
City                0
Region              0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Rating              0
Payment_Method      0
dtype: int64

          Order_ID    Quantity   Unit_Price  Discount_Percent   Total_Sales      Rating
count   100.000000  100.000000   100.000000        100.000000    100.000000  100.000000
mean   1050.500000    2.940000  1647.000000          6.500000   4472.629500    4.322000
std      29.011492    1.391315   970.054669          6.092718   3324.306691    0.414285
min    1001.000000    1.000000   499.000000          0.000000    449.100000    3.500000
25%    1025.750000    2.000000   799.000000          0.000000   1948.050000    4.100000
50%    1050.500000    3.000000  1499.000000          5.000000   3228.300000    4.300000
75%    1075.250000    4.000000  2499.000000         11.250000   6427.562500    4.700000
max    1100.000000    5.000000  3499.000000         15.000000  13995.000000    5.000000

## 2. Data Selection

Selecting specific columns and rows using label-based (`.loc`) and position-based (`.iloc`) indexing.

In [5]:

sales_view = df[['Order_ID', 'Product', 'Category', 'City', 'Payment_Method', 'Total_Sales']]
sales_view.head()

   Order_ID              Product     Category       City    Payment_Method  Total_Sales
0      1001  Wireless Headphones  Electronics  Hyderabad  Cash on Delivery      4497.00
1      1002        Running Shoes       Sports      Jammu  Cash on Delivery      2799.00
2      1003           Power Bank  Electronics    Chennai  Cash on Delivery      2038.30
3      1004  Mechanical Keyboard  Electronics    Lucknow        Debit Card      9496.20
4      1005          Smart Watch  Electronics      Jammu               UPI      3134.05

In [6]:

df.iloc[0:5]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [7]:

df.loc[df['Order_ID'] == 1010, ['Order_ID', 'Customer', 'Product', 'Total_Sales', 'Payment_Method']]

   Order_ID    Customer Product  Total_Sales Payment_Method
9      1010  Aman Kumar  Jacket       8996.4    Credit Card

In [9]:

high_value_orders = df[df['Total_Sales'] > 10000]
print(f"Number of high-value orders (> ₹10,000): {len(high_value_orders)}")
high_value_orders[['Order_ID', 'Product', 'City', 'Total_Sales']]

Number of high-value orders (> ₹10,000): 6

    Order_ID        Product       City  Total_Sales
12      1013         Jacket    Lucknow     10620.75
47      1048   Coffee Maker    Lucknow     10497.00
48      1049  Running Shoes     Mumbai     13995.00
52      1053  Running Shoes  Hyderabad     13295.25
84      1085   Coffee Maker  Hyderabad     12596.40
89      1090    Cricket Bat    Lucknow     12495.00

In [8]:

electronics_upi = df[(df['Category'] == 'Electronics') & (df['Payment_Method'] == 'UPI')]
electronics_upi[['Order_ID', 'Product', 'City', 'Total_Sales', 'Payment_Method']]

    Order_ID              Product        City  Total_Sales Payment_Method
4       1005          Smart Watch       Jammu      3134.05            UPI
14      1015  Wireless Headphones     Kolkata      2998.00            UPI
27      1028  Wireless Headphones  Chandigarh      5696.20            UPI
36      1037           Power Bank        Pune      2038.30            UPI
46      1047       Wireless Mouse   Bengaluru      3820.75            UPI
61      1062  Mechanical Keyboard      Mumbai      7497.00            UPI
68      1069       Wireless Mouse   Ahmedabad      1708.10            UPI

In [10]:

discounted_top_rated = df[(df['Discount_Percent'] > 0) & (df['Rating'] >= 4.5)]
print(f"Discounted orders rated 4.5+: {len(discounted_top_rated)}")
discounted_top_rated[['Order_ID', 'Product', 'Discount_Percent', 'Rating', 'Total_Sales']].head()

Discounted orders rated 4.5+: 32

    Order_ID      Product  Discount_Percent  Rating  Total_Sales
2       1003   Power Bank                15     4.6      2038.30
9       1010       Jacket                10     4.7      8996.40
11      1012  Cricket Bat                10     4.6      4498.20
12      1013       Jacket                15     4.8     10620.75
20      1021     Yoga Mat                10     4.7       809.10

In [ ]:

city_orders = df[df['City'] == 'Hyderabad']
city_orders[['Order_ID', 'Product', 'Category', 'Total_Sales']]

    Order_ID              Product        Category  Total_Sales
0       1001  Wireless Headphones     Electronics      4497.00
10      1011         Coffee Maker  Home & Kitchen      6998.00
16      1017          Cricket Bat          Sports      7497.00
28      1029  Wireless Headphones     Electronics      5696.20
52      1053        Running Shoes          Sports     13295.25
84      1085         Coffee Maker  Home & Kitchen     12596.40
92      1093          Cricket Bat          Sports      8496.60

In [ ]:

top5_orders = df.sort_values('Total_Sales', ascending=False).head(5)
top5_orders[['Order_ID', 'Product', 'City', 'Total_Sales']]

    Order_ID        Product       City  Total_Sales
48      1049  Running Shoes     Mumbai     13995.00
52      1053  Running Shoes  Hyderabad     13295.25
84      1085   Coffee Maker  Hyderabad     12596.40
89      1090    Cricket Bat    Lucknow     12495.00
12      1013         Jacket    Lucknow     10620.75

In [ ]:

bottom5_orders = df.sort_values('Total_Sales', ascending=True).head(5)
bottom5_orders[['Order_ID', 'Product', 'City', 'Total_Sales']]

    Order_ID             Product        City  Total_Sales
5       1006       The Alchemist       Kochi       449.10
62      1063       The Alchemist  Chandigarh       449.10
73      1074       Atomic Habits     Lucknow       539.10
96      1097             T-Shirt      Mumbai       679.15
60      1061  Python Programming   Bengaluru       711.55

In [ ]:

multi_sorted = df.sort_values(['Category', 'Total_Sales'], ascending=[True, False])
multi_sorted[['Category', 'Order_ID', 'Product', 'Total_Sales']].head(10)

   Category  Order_ID                  Product  Total_Sales
99    Books      1100    Data Science Handbook      4495.00
29    Books      1030       Python Programming      2996.00
90    Books      1091            Atomic Habits      2995.00
87    Books      1088       Python Programming      2546.60
72    Books      1073            Atomic Habits      2545.75
63    Books      1064            Atomic Habits      2396.00
66    Books      1067            The Alchemist      2245.50
86    Books      1087            Atomic Habits      2036.60
98    Books      1099  Machine Learning Basics      1998.00
88    Books      1089  Machine Learning Basics      1798.20

In [ ]:
category_summary = df.groupby('Category').agg(
    total_sales=('Total_Sales', 'sum'),
    avg_sales=('Total_Sales', 'mean'),
    max_sales=('Total_Sales', 'max'),
    min_sales=('Total_Sales', 'min'),
    total_quantity=('Quantity', 'sum'),
    num_orders=('Order_ID', 'count')
).round(2).sort_values('total_sales', ascending=False)

category_summary

                total_sales  avg_sales  max_sales  min_sales  total_quantity  num_orders
Category
Sports            136026.45    5441.06   13995.00     759.05              79          25
Home & Kitchen    113329.90    5396.66   12596.40    1188.30              59          21
Electronics        92086.00    4846.63    9496.20    1708.10              57          19
Clothing           69028.20    4930.59   10620.75     679.15              39          14
Books              36792.40    1752.02    4495.00     449.10              60          21

In [ ]:
city_summary = df.groupby('City').agg(
    total_sales=('Total_Sales', 'sum'),
    avg_sales=('Total_Sales', 'mean'),
    total_quantity=('Quantity', 'sum'),
    num_orders=('Order_ID', 'count')
).round(2).sort_values('total_sales', ascending=False)

city_summary

             total_sales  avg_sales  total_quantity  num_orders
City
Hyderabad       59076.45    8439.49              25           7
Chennai         47493.20    4749.32              29          10
Lucknow         46194.65    7699.11              22           6
Pune            41908.55    4190.86              34          10
Mumbai          41457.80    5182.23              23           8
Kochi           37257.50    4139.72              29           9
Chandigarh      34539.65    4317.46              22           8
Delhi           30882.80    5147.13              18           6
Jaipur          25534.00    3647.71              17           7
Kolkata         20169.00    2881.29              24           7
Jammu           16059.75    2676.62              11           6
Ahmedabad       14788.70    2464.78              12           6
Bengaluru       13524.30    3381.08              14           4
Srinagar        11778.60    2355.72              12           5
Bhubaneswar      6598.00    6598.00               2           1

In [ ]:

city_summary.head(5)

           total_sales  avg_sales  total_quantity  num_orders
City
Hyderabad     59076.45    8439.49              25           7
Chennai       47493.20    4749.32              29          10
Lucknow       46194.65    7699.11              22           6
Pune          41908.55    4190.86              34          10
Mumbai        41457.80    5182.23              23           8

In [ ]:
product_summary = df.groupby('Product').agg(
    total_sales=('Total_Sales', 'sum'),
    total_quantity=('Quantity', 'sum'),
    num_orders=('Order_ID', 'count'),
    avg_rating=('Rating', 'mean')
).round(2).sort_values('total_sales', ascending=False)

print("Top 5 best-selling products by total sales:")
product_summary.head(5)

Top 5 best-selling products by total sales:

                     total_sales  total_quantity  num_orders  avg_rating
Product
Coffee Maker            51610.25              16           7        4.51
Jacket                  47106.15              20           5        4.52
Cricket Bat             41483.40              18           5        4.22
Running Shoes           41285.25              15           5        4.24
Wireless Headphones     33877.40              23           7        4.16

In [ ]:

top_qty_product = product_summary.sort_values('total_quantity', ascending=False).head(1)
top_qty_product

                     total_sales  total_quantity  num_orders  avg_rating
Product
Wireless Headphones      33877.4              23           7        4.16

In [ ]:
payment_summary = df.groupby('Payment_Method').agg(
    total_sales=('Total_Sales', 'sum'),
    avg_sales=('Total_Sales', 'mean'),
    num_orders=('Order_ID', 'count')
).round(2).sort_values('total_sales', ascending=False)

payment_summary

                  total_sales  avg_sales  num_orders
Payment_Method
Credit Card         106540.25    4842.74          22
Debit Card           98064.90    4903.25          20
Net Banking          96371.25    5668.90          17
UPI                  96163.25    3698.59          26
Cash on Delivery     50123.30    3341.55          15

In [ ]:
category_payment = df.groupby(['Category', 'Payment_Method'])['Total_Sales'].agg(['sum', 'count']).round(2)
category_payment.rename(columns={'sum': 'total_sales', 'count': 'num_orders'})

                                 total_sales  num_orders
Category       Payment_Method
Books          Cash on Delivery      1160.65           2
               Credit Card           6912.85           5
               Debit Card            9838.80           4
               Net Banking           5779.60           3
               UPI                  13100.50           7
Clothing       Cash on Delivery      8055.60           3
               Credit Card          15072.60           2
               Debit Card           10795.00           2
               Net Banking          23812.75           3
               UPI                  11292.25           4
Electronics    Cash on Delivery     16519.00           4
               Credit Card          12294.20           2
               Debit Card           31883.40           5
               Net Banking           4497.00           1
               UPI                  26892.40           7
Home & Kitchen Cash on Delivery     12333.40           3
               Credit Card          12919.30           3
               Debit Card           26209.85           5
               Net Banking          32180.25           5
               UPI                  29687.10           5
Sports         Cash on Delivery     12054.65           3
               Credit Card          59341.30          10
               Debit Card           19337.85           4
               Net Banking          30101.65           5
               UPI                  15191.00           3

In [ ]:
overall_stats = {
    'Total Sales (all orders)': df['Total_Sales'].sum(),
    'Average Sales per Order': df['Total_Sales'].mean(),
    'Highest Single Order Value': df['Total_Sales'].max(),
    'Lowest Single Order Value': df['Total_Sales'].min(),
    'Total Quantity Sold': df['Quantity'].sum(),
    'Total Number of Orders': df['Order_ID'].nunique()
}

for k, v in overall_stats.items():
    print(f"{k}: {round(v, 2) if isinstance(v, float) else v}")

Total Sales (all orders): 447262.95
Average Sales per Order: 4472.63
Highest Single Order Value: 13995.0
Lowest Single Order Value: 449.1
Total Quantity Sold: 294
Total Number of Orders: 100

In [ ]:

print("Highest-value order:")
display(df.loc[df['Total_Sales'].idxmax()])

print("\nLowest-value order:")
display(df.loc[df['Total_Sales'].idxmin()])

Highest-value order:

Order_ID                           1049
Order_Date          2026-03-02 00:00:00
Customer                   Ishita Gupta
City                             Mumbai
Region                             West
Category                         Sports
Product                   Running Shoes
Quantity                              5
Unit_Price                         2799
Discount_Percent                      0
Total_Sales                     13995.0
Rating                              4.0
Payment_Method              Net Banking
Name: 48, dtype: object

Lowest-value order:

Order_ID                           1006
Order_Date          2026-01-21 00:00:00
Customer                      Manya Rao
City                              Kochi
Region                            South
Category                          Books
Product                   The Alchemist
Quantity                              1
Unit_Price                          499
Discount_Percent                     10
Total_Sales                       449.1
Rating                              4.2
Payment_Method         Cash on Delivery
Name: 5, dtype: object

In [ ]:
top_category = category_summary['total_sales'].idxmax()
top_product = product_summary['total_sales'].idxmax()
top_city = city_summary['total_sales'].idxmax()
top_payment = payment_summary['total_sales'].idxmax()

print(f"Top-performing category : {top_category} (₹{category_summary.loc[top_category, 'total_sales']:,.2f})")
print(f"Top-performing product  : {top_product} (₹{product_summary.loc[top_product, 'total_sales']:,.2f})")
print(f"Top city by sales       : {top_city} (₹{city_summary.loc[top_city, 'total_sales']:,.2f})")
print(f"Most-used payment method: {top_payment} (₹{payment_summary.loc[top_payment, 'total_sales']:,.2f})")

Top-performing category : Sports (₹136,026.45)
Top-performing product  : Coffee Maker (₹51,610.25)
Top city by sales       : Hyderabad (₹59,076.45)
Most-used payment method: Credit Card (₹106,540.25)