In [4]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

df = pd.read_csv('Day7_Student_Dataset.csv')
print("Dataset loaded successfully.")

Dataset loaded successfully.

In [5]:
df.head()

   Student_ID          Name  Age            Course  Marks  Attendance_Percentage      City
0        1001  Aarav Sharma   19      Data Science   87.0                   91.0  Srinagar
1        1002     Zoya Khan   20                AI   92.0                   95.0     Delhi
2        1003   Rohan Mehta   18  Computer Science   76.0                   82.0    Mumbai
3        1004  Ananya Singh   21      Data Science   81.0                   88.0  Srinagar
4        1005     Kabir Ali   19                AI   69.0                   76.0   Lucknow

In [6]:
df.head(10)

   Student_ID          Name  Age            Course  Marks  Attendance_Percentage       City
0        1001  Aarav Sharma   19      Data Science   87.0                   91.0   Srinagar
1        1002     Zoya Khan   20                AI   92.0                   95.0      Delhi
2        1003   Rohan Mehta   18  Computer Science   76.0                   82.0     Mumbai
3        1004  Ananya Singh   21      Data Science   81.0                   88.0   Srinagar
4        1005     Kabir Ali   19                AI   69.0                   76.0    Lucknow
5        1006  Ishita Gupta   20  Computer Science   88.0                   93.0  Bengaluru
6        1007  Aditya Verma   22      Data Science   95.0                   97.0       Pune
7        1008    Sara Ahmed   19                AI   73.0                    NaN  Hyderabad
8        1009    Arjun Nair   18  Computer Science   84.0                   86.0      Kochi
9        1010    Mehak Bhat   21      Data Science   79.0                   90.0   Srinagar

In [7]:
df.tail()

    Student_ID          Name  Age            Course  Marks  Attendance_Percentage       City
20        1021    Aman Kumar   18  Computer Science   74.0                   78.0      Delhi
21        1022    Alina Shah   19      Data Science   96.0                   98.0   Srinagar
22        1023   Nikhil Sood   22                AI   78.0                   83.0       Pune
23        1024   Maryam Khan   20  Computer Science   85.0                   88.0  Hyderabad
24        1025  Reyansh Jain   21      Data Science   80.0                   84.0    Kolkata

In [8]:
df.sample(5, random_state=42)

    Student_ID          Name  Age            Course  Marks  Attendance_Percentage       City
8         1009    Arjun Nair   18  Computer Science   84.0                   86.0      Kochi
16        1017     Dev Patel   19                AI   86.0                   89.0  Ahmedabad
0         1001  Aarav Sharma   19      Data Science   87.0                   91.0   Srinagar
23        1024   Maryam Khan   20  Computer Science   85.0                   88.0  Hyderabad
11        1012     Aisha Mir   19  Computer Science   68.0                   72.0      Delhi

In [9]:
print("Shape (rows, columns):", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Shape (rows, columns): (25, 7)
Number of rows: 25
Number of columns: 7

In [10]:
print("Column names:")
list(df.columns)

Column names:

['Student_ID',
 'Name',
 'Age',
 'Course',
 'Marks',
 'Attendance_Percentage',
 'City']

In [11]:
print("Index details:")
df.index

Index details:

RangeIndex(start=0, stop=25, step=1)

In [12]:
df.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

In [13]:
df.dtypes.value_counts()

object     3
int64      2
float64    2
Name: count, dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

In [15]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

In [16]:
df.describe(include='object')

                Name        Course      City
count             25            25        24
unique            25             3        13
top     Aarav Sharma  Data Science  Srinagar
freq               1             9         6

In [17]:
df.describe(include='all')

         Student_ID          Name        Age        Course      Marks  Attendance_Percentage      City
count     25.000000            25  25.000000            25  24.000000              24.000000        24
unique          NaN            25        NaN             3        NaN                    NaN        13
top             NaN  Aarav Sharma        NaN  Data Science        NaN                    NaN  Srinagar
freq            NaN             1        NaN             9        NaN                    NaN         6
mean    1013.000000           NaN  20.000000           NaN  82.250000              87.083333       NaN
std        7.359801           NaN   1.414214           NaN   8.689074               7.252686       NaN
min     1001.000000           NaN  18.000000           NaN  68.000000              72.000000       NaN
25%     1007.000000           NaN  19.000000           NaN  75.500000              82.750000       NaN
50%     1013.000000           NaN  20.000000           NaN  82.500000              88.000000       NaN
75%     1019.000000           NaN  21.000000           NaN  89.250000              92.250000       NaN
max     1025.000000           NaN  23.000000           NaN  96.000000              98.000000       NaN

In [18]:
missing = df.isnull().sum()
missing_pct = (df.isnull().mean() * 100).round(2)

missing_summary = pd.DataFrame({'missing_count': missing, 'missing_percent': missing_pct})
missing_summary[missing_summary['missing_count'] > 0]

                       missing_count  missing_percent
Marks                              1              4.0
Attendance_Percentage              1              4.0
City                               1              4.0

In [19]:
df[df.isnull().any(axis=1)]

    Student_ID        Name  Age        Course  Marks  Attendance_Percentage       City
7         1008  Sara Ahmed   19            AI   73.0                    NaN  Hyderabad
13        1014  Sana Malik   18            AI   89.0                   92.0        NaN
18        1019   Yusuf Dar   20  Data Science    NaN                   87.0   Srinagar

In [20]:
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    print(f"{col}: {df[col].nunique()} unique values")
    print(df[col].unique())
    print()

Name: 25 unique values
['Aarav Sharma' 'Zoya Khan' 'Rohan Mehta' 'Ananya Singh' 'Kabir Ali'
 'Ishita Gupta' 'Aditya Verma' 'Sara Ahmed' 'Arjun Nair' 'Mehak Bhat'
 'Vivaan Kapoor' 'Aisha Mir' 'Rahul Das' 'Sana Malik' 'Karan Joshi'
 'Hiba Sheikh' 'Dev Patel' 'Manya Rao' 'Yusuf Dar' 'Priya Menon'
 'Aman Kumar' 'Alina Shah' 'Nikhil Sood' 'Maryam Khan' 'Reyansh Jain']

Course: 3 unique values
['Data Science' 'AI' 'Computer Science']

City: 13 unique values
['Srinagar' 'Delhi' 'Mumbai' 'Lucknow' 'Bengaluru' 'Pune' 'Hyderabad'
 'Kochi' 'Jaipur' 'Kolkata' nan 'Chandigarh' 'Ahmedabad' 'Chennai']

In [21]:
print("Number of fully duplicated rows:", df.duplicated().sum())
print("Number of duplicated Student_IDs:", df['Student_ID'].duplicated().sum())

Number of fully duplicated rows: 0
Number of duplicated Student_IDs: 0